const LOGIN_PENDING = "LOGIN_PENDING";
const PARTIAL_LOGIN_COMPLETED = "PARTIAL_LOGIN_COMPLETED";
const LOGIN_COMPLETED = "LOGIN_COMPLETED";
const LOGIN_ERROR = "LOGIN_ERROR";
const SIGNUP_PENDING = "SIGNUP_PENDING";
const SIGNUP_COMPLETED = "SIGNUP_COMPLETED";
const SIGNUP_ERROR = "SIGNUP_ERROR";
const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING";
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
const LOGOUT = "LOGOUT";
const REMEMBER_ME = "REMEMBER_ME";
const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export {
  LOGIN_PENDING,
  PARTIAL_LOGIN_COMPLETED,
  LOGIN_COMPLETED,
  LOGIN_ERROR,
  LOGOUT,
  REMEMBER_ME,
  CLOSE_SNACKBAR,
  SIGNUP_PENDING,
  SIGNUP_COMPLETED,
  SIGNUP_ERROR,
  RESET_PASSWORD_PENDING,
  RESET_PASSWORD_SUCCESS,
};
