const EMAIL_PENDING = "EMAIL_PENDING";
const EMAIL_COMPLETED = "EMAIL_COMPLETED";
const EMAIL_ERROR = "EMAIL_ERROR";
const EMAIL_SUCCESS = "EMAIL_SUCCESS";
const EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED";

export {
  EMAIL_PENDING,
  EMAIL_COMPLETED,
  EMAIL_ERROR,
  EMAIL_SUCCESS,
  EMAIL_ALREADY_VERIFIED,
};
